<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container46hYNdX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container46hYNdX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container46hYNdX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container46hYNdX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container46hYNdX\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => '46hYNdX',
    'container.build_id' => 'b94effb4',
    'container.build_time' => 1546599301,
), __DIR__.\DIRECTORY_SEPARATOR.'Container46hYNdX');
